### ISSUE TITLE
GetName crash

### ISSUE THREAD

**Issue by Lessyzz** [FigmaFan/IL2CPP-BRIDGE#1]
I am using original IL2CPP-Resolver version. 
When I run this code

```
Unity::il2cppArray<Unity::CGameObject*>* m_pObjects = Unity::Object::FindObjectsOfType<Unity::CGameObject>(UNITY_GAMEOBJECT_CLASS);

    for (uintptr_t u = 0U; m_pObjects->m_uMaxLength > u; ++u)
    {
        Unity::CGameObject* m_pObject = m_pObjects->m_pValues[u];
        if (!m_pObject) continue;

        cout << m_pObject->GetName();
    }
```
    
The game crashes when the GetName function runs do you have any idea?

**Comment by FigmaFan** [comment]
This library is independent of sneaky evils il2cpp resolver, therefore I can't help you with this issue. Please open an issue in the original il2cpp resolver repo.
