### ISSUE TITLE
FindObjectsByType

### ISSUE THREAD

**Issue by Lessyzz** [FigmaFan/IL2CPP-BRIDGE#3]
Is there any way to use **FindObjectsByType** because the game does not have **FindObjectsOfType**

**Comment by FigmaFan** [comment]
Are you sure that the game does not have the **FindObjectsOfType** method? GameAssembly.dll usually contains the assembly **UnityEngine.CoreModule** where you can find **FindObjectsOfType** inside of the **Object** class (part of the **UnityEngine** namespace).

**Comment by Lessyzz** [comment]
I checked there but FindObjectsOfType is not there. I found FindObjectsByType and I can only use it. Is it possible?

**Comment by FigmaFan** [comment]
sure, you should be able to get its method info by calling `get_method("UnityEngine", "Object", "FindObjectsByType", "UnityEngine.CoreModule");` Check your dumps to find out which arguments you have to pass.

**Comment by Lessyzz** [comment]
Thanks!
